name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Only trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Extract Version from Tag
        id: extract_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
          mkdir engine-jar-build
          mv build/libs/engine-*.jar engine-jar-build/engine-${{ steps.extract_version.outputs.version }}.jar
          cd engine-jar-build
          zip -r ../engine-${{ steps.extract_version.outputs.version }}.zip *
          cd ..
          cp -r engine-jar-build engine-aws-upload
          mv engine-aws-upload/engine-*.jar engine-aws-upload/engine.jar

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: ${{ steps.extract_version.outputs.version }}
          draft: true

      - name: Upload Archive to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: engine-${{ steps.extract_version.outputs.version }}.zip
          asset_name: engine-${{ steps.extract_version.outputs.version }}.zip
          asset_content_type: application/octet-stream

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: engine-${{ steps.extract_version.outputs.version }}
          path: build/libs/engine-${{ steps.extract_version.outputs.version }}.jar

      - uses: shallwefootball/s3-upload-action@4350529f410221787ccf424e50133cbc1b52704e
        name: Upload jar to S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'engine-aws-upload'
          destination_dir: "./"
